nmHoistingLimits: workspaces

nodeLinker: node-modules

packageExtensions:
  "@parcel/packager-html@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/packager-svg@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/plugin@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/reporter-cli@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/reporter-dev-server@*":
    dependencies:
      "@types/express": "*"
  "@parcel/transformer-postcss@*":
    dependencies:
      postcss: "*"
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-berry.cjs
